Repository POO-I-Turma-853-Grupo-04/Projeto-Grupo-4-POO-I, pull requests merged in 2022-06, with the labels that each got.

#13 Atualizando o nome da class Main
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/TestaEmprestimo.cs
Labels: bug

#14 Criando classe Garantia
  Projeto - Grupo 04 Turma 853/.vs/Projeto - Grupo 04 Turma 853/v17/.suo
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Garantia.cs
Labels: class

#15 Adicionando classe Veiculo
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Veiculo.cs
Labels: update class

#20 Adicionando a classe Garantia
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Garantia.cs
Labels: update class

#25 Atualizando a classe Veiculo
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Veiculo.cs
Labels: update class

#27 Adicionando Main
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Auxiliar.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Cliente.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Contrato.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Funcionario.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Pessoa.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Sistema.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/TestaEmprestimo.cs
Labels: new class, update class

#28 Atualizando o main com as escolhas de Garantia
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Garantia.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Imovel.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/TestaEmprestimo.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Veiculo.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/bin/Debug/net6.0/Grupo_04_Turma_853.dll
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/bin/Debug/net6.0/Grupo_04_Turma_853.pdb
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/obj/Debug/net6.0/Grupo_04_Turma_853.GeneratedMSBuildEditorConfig.editorconfig
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/obj/Debug/net6.0/Grupo_04_Turma_853.csproj.AssemblyReference.cache
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/obj/Debug/net6.0/Grupo_04_Turma_853.csproj.CoreCompileInputs.cache
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/obj/Debug/net6.0/Grupo_04_Turma_853.dll
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/obj/Debug/net6.0/Grupo_04_Turma_853.pdb
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/obj/Debug/net6.0/ref/Grupo_04_Turma_853.dll
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/obj/Debug/net6.0/refint/Grupo_04_Turma_853.dll
Labels: update class

#32 Atualizando o layout do sistema
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/AnaliseRisco.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Cliente.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Contrato.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Emprestimo.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Garantia.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Imovel.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Sistema.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/TestaEmprestimo.cs
  Projeto - Grupo 04 Turma 853/Grupo_04_Turma_853/Veiculo.cs
Labels: update class
